DROP TABLE IF EXISTS STORES;
CREATE TABLE STORES  (
    ID INTEGER AUTO_INCREMENT  PRIMARY KEY,
    LOCATION_ID VARCHAR(50) NOT NULL,
    PARENT_ID VARCHAR(50),
    AMOUNT DECIMAL(10,2),
    PRIMARY KEY(ID)
);

ALTER TABLE STORES
    ADD CONSTRAINT idx_stores_uq UNIQUE(LOCATION_ID, PARENT_ID);
